//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATIONS
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string NOTES { get; set; }
        public Nullable<byte> ISDELETE { get; set; }
        public Nullable<byte> ISACTIVE { get; set; }
    }
}
